### ISSUE TITLE
Understand Object-oriented programming

### ISSUE THREAD

**Issue by PaulZbigniew** [KaufmannLukas/ds-ultimate-tic-tac-toe#13]
- class objects
- class inside another class => `Game._Player()`
- `@property` => built-in decorater for a function => "decorates the function"; i.e. `current_player` function can be treated as a variable, not as function; 
- `|` = `or`
- `finished_games` => second part of the code of the line is for creating a two dimensional array out of the one dimensional won/not won array
-

**Comment by thamban15** [comment]
Review sessions by Nils on game, environment’s ..
